# Generated by Django 5.0.4 on 2024-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='works_from',
            field=models.DateField(null=True),
        ),
    ]
