# Generated by Django 5.0.4 on 2024-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_rename_works_from_doctor_works_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='target',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
