# Generated by Django 5.0.4 on 2024-04-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
