# Generated by Django 5.0.4 on 2024-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_appointment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='target',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
