# Generated by Django 5.0.4 on 2024-04-23 10:14

import clinic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_alter_appointment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimages',
            name='image',
            field=models.ImageField(default='clinic/static/no_photo.png', upload_to=clinic.models.ServiceImages.image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Женский'), ('M', 'Мужской')], default='M', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=clinic.models.ServiceVideo.video_path)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_video', to='clinic.service')),
            ],
        ),
    ]
