# Generated by Django 5.0.4 on 2024-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_alter_appointment_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['-date'], name='clinic_appo_date_0dd3f4_idx'),
        ),
    ]
